### ISSUE TITLE
Ver sobre un proyecto en sicoes

### ISSUE THREAD

**Issue by CMedinapr3** [Del-Buho/Del-buho#1]
Se debia escoger un proyecto en la pagina de sicoes. 
Se presentaron 2 opciones que fueron rechazadas ya que no eran para desarrollo de software. 
Finalmente se escogio y acepto el proyecto 
https://www.infosicoes.com/desarrollo-de-software-para-el-registro-sanitario-y-fitosanitario-de-empresas-y-productos-del-senasag-lct392188.html

**Comment by hrnn** [comment]
Los dos proyectos que mencionaron en upbvirtual, no son proyectos de desarrollo de software si no mas bien de compra, busquen otros proyectos podrian usar otras palabras clave como, desarrollo sistema, informática o parecidos, adicionalmente busquen todos, incluso pasados, ejemplo:

![WhatsApp Image 2019-11-19 at 8 13 19 PM](https://user-images.githubusercontent.com/854676/69289342-90e22980-0bd2-11ea-9e74-a724052294fc.jpeg)

**Comment by CMedinapr3** [comment]
https://www.infosicoes.com/desarrollo-de-software-para-el-registro-sanitario-y-fitosanitario-de-empresas-y-productos-del-senasag-lct392188.html

**Comment by CMedinapr3** [comment]
Objetivo General
Desarrollo y puesta en producción del sistema informático para el registro sanitario y fitosanitario de empresas y productos del SENASAG utilizando herramientas libres.

**Comment by CMedinapr3** [comment]
Ya se escogio y se tiene como proyecto el propuesto por el Beni
