### ISSUE TITLE
Crear pagina principal de la wiki

### ISSUE THREAD

**Issue by CMedinapr3** [Del-Buho/Del-buho#2]
Crear una wiki sobre el proyecto.
Debe contener el objetivo del proyecto.

**Comment by CMedinapr3** [comment]
Se realizo una introducción, descripción del proyecto, requerimientos generales y los usuarios para la wiki

**Comment by MichaelVelarde** [comment]
Se corrigio los casos de uso, mockups , arquitectura de software de acuerdo a lo indicado para la primera revision.
