### ISSUE TITLE
Definir si sera un proyecto Mobile o Web

### ISSUE THREAD

**Issue by CMedinapr3** [Del-Buho/Del-buho#4]
Se debe escoger si el proyecto sera Web o mobile. 
Debido a la experiencia del equipo con bases de datos en Web.
El proyecto se realizara para la Web

**Comment by CMedinapr3** [comment]
Sera un proyecto web

**Comment by MichaelVelarde** [comment]
Debido a que se requiere una base de datos que el cliente pueda manejar decidimos que se haria en web , por la experiencia con bases de datos en webs
