### ISSUE TITLE
Definir la audiencia de la applicación

### ISSUE THREAD

**Issue by hrnn** [Del-Buho/Del-buho#8]
El proyecto es para el uso de la empresa Senasag.
Esta tiene que poder ver/editar los datos sobre las empresas que usan sus productos, debido a esto nuestra audiencia seria:
Cliente (administrador ,usuario).

**Comment by MichaelVelarde** [comment]
El proyecto es para que lo utilize la empresa Senasag, debido a esto la audiencia seria el cliente
