### ISSUE TITLE
Creacion de mockups

### ISSUE THREAD

**Issue by CMedinapr3** [Del-Buho/Del-buho#9]
Se realizaron los mockups para tener una mejor idea sobre el proyecto. 
Se crearon con ayuda de la herramienta online Gliffy. 
Link a los mockups:
https://go.gliffy.com/go/share/shy6uoht80w5e1osh932

**Comment by MichaelVelarde** [comment]
Ya se tiene una idea de la web que se desea realizar , los mockups se hicieron con gliffy. Para ver los mockups acceder al link de arriba.
